config/routes.rb
Rails.application.routes.draw do
  root "fronts#top"
  post "/result", to: "fronts#result"
  post "/map_search", to: "fronts#map_search"
  get "/calc_price_form", to: "fronts#calc_price_form"
  get "/karaoke_map", to: "fronts#karaoke_map"
  resources :karaoke_shops do
  end
end

app/controllers/fronts_controller.rb
class FrontsController < ApplicationController

  def top
  end

  def calc_price_form
  end

  def karaoke_map
    @karaoke_shops = KaraokeShop.where(karaoke_kind_id: 3)
  end

  def map_search
    
  end

  def result
    return @all_display_data = [] if start_time == end_time
    shops = KaraokeShop.where(karaoke_kind_id: params[:kind]&.values).map { |shop| shop.object(params[:date],start_time,end_time) }
    @all_display_data = shops.map {|shop| shop.display_data_list}.flatten.select{|display_data| display_data.charge > 0}
  end

  def edit
  end

  def create
    respond_to do |format|
      if @front.save
        format.html { redirect_to @front, notice: 'Front was successfully created.' }
        format.json { render :show, status: :created, location: @front }
      else
        format.html { render :new }
        format.json { render json: @front.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @front.update(front_params)
        format.html { redirect_to @front, notice: 'Front was successfully updated.' }
        format.json { render :show, status: :ok, location: @front }
      else
        format.html { render :edit }
        format.json { render json: @front.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @front.destroy
    respond_to do |format|
      format.html { redirect_to fronts_url, notice: 'Front was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def start_time
    OnlyTime.freetime(params[:start_time],params[:end_time])[:starttime]
  end

  def end_time
    OnlyTime.freetime(params[:start_time],params[:end_time])[:endtime]
  end
end

app/helpers/fronts_helper.rb
module FrontsHelper
end

app/views/fronts/_form.html.erb
<%= form_with(model: front, local: true) do |form| %>
  <% if front.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(front.errors.count, "error") %> prohibited this front from being saved:</h2>

      <ul>
      <% front.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fronts/calc_price_form.html.erb
<p id="notice"><%= notice %></p>

<h1>カラオケ料金検索</h1>

<%= form_with(url: result_path, local: true) do |form| %>

  <div class="field">
    <%= form.label :date, "曜日" %>
    <%= select_tag "[date]", options_for_select(EasySettings.date) %>
  </div>

  <div class="field">
    <%= form.label :start_time, "開始時間" %>
    <%= time_select "[start_time]", :start_time, :minute_step => 10 %>
  </div>

  <div class="field">
    <%= form.label :end_time, "終了時間" %>
    <%= time_select "[end_time]", :end_time, :minute_step => 10 %>
  </div>

  <div class="field">
    <%= form.label :display_kind, "表示店舗" %>
  </div>

  <div class="field">
    <%= check_box_tag "kind[karaokekan]", 1, true, {} %>カラオケ館
  </div>

  <div class="field">
    <%= check_box_tag "kind[utahiroba]", 2, true, {} %>歌広場
  </div>

  <div class="field">
    <%= check_box_tag "kind[tetsujin]", 3, true, {} %>カラオケの鉄人
  </div>

  <div class="field">
    <%= check_box_tag "kind[bigecoh]", 4, true, {} %>ビッグエコー
  </div>

  <div class="field">
    <%= check_box_tag "kind[banban]", 5, true, {} %>カラオケバンバン
  </div>

  <div class="actions">
    <%= form.submit "料金を計算", class:"btn btn-primary" %>
  </div>

<% end %>

<br>
<%= link_to '新規店舗登録', new_karaoke_shop_path, class:"btn btn-primary" %>

app/views/fronts/edit.html.erb
<h1>Editing Front</h1>

<%= render 'form', front: @front %>

<%= link_to 'Show', @front %> |
<%= link_to 'Back', fronts_path %>

app/views/fronts/karaoke_map.html.erb
<h1>カラオケ店舗検索</h1>

<%= form_with(url: map_search_path, local: true) do |form| %>
  <div class="field">
    <%= select_tag "from_place", options_for_select([["現在地","現在地"],["指定したピン","ピン"]]) %>から
    <%= select_tag "distance", options_for_select([["全ての店舗",0],["300m以内",300],["500m以内",500],["1km以内",1000],["3km以内",3000],["5km以内",5000]]) %>で
    <%= form.submit "検索" %>
  </div>
<% end %>

<div id="maps"></div>

<script src="//maps.googleapis.com/maps/api/js?key=<%= ENV['MAP_API_KEY'] %>&libraries=geometry&callback=initMap" async></script>
<script>
  function initMap() {
    if( navigator.geolocation ){
      navigator.geolocation.getCurrentPosition(function(position) {
        var CurrentPosition = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
        var mapArea = document.getElementById('maps');
        var mapOptions = {
          center: CurrentPosition,
          zoom: 16,
        };
        var map = new google.maps.Map(mapArea, mapOptions);
        var current_point_marker = new google.maps.Marker({
          map: map,
          position: CurrentPosition,
          title: "現在地",
          icon: {
        		fillColor: "#7FFFD4",                //塗り潰し色
        		fillOpacity: 0.8,                    //塗り潰し透過率
        		path: google.maps.SymbolPath.CIRCLE, //円を指定
        		scale: 7,                           //円のサイズ
        		strokeColor: "#4169E1",              //枠の色
        		strokeWeight: 1.0                    //枠の透過率
        	}
        });
        var geocoder = new google.maps.Geocoder();
        <% @karaoke_shops.each do |karaoke_shop| %>
          geocoder.geocode(
            {
            'address': '<%= karaoke_shop.address %>'
            },
            function(results, status) {
              if (status === google.maps.GeocoderStatus.OK) {
                var ShopPosition = results[0].geometry.location
                var distance = google.maps.geometry.spherical.computeDistanceBetween(CurrentPosition,ShopPosition);
                if (distance < 10000) {
                  var marker = new google.maps.Marker({
                    position: ShopPosition,
                    title: '<%= karaoke_shop.name %>',
                    map: map
                  });
                  var window_content = '<div class="address">' +
                                         '<%= karaoke_shop.address %>' +
                                       '</div>' +
                                       '<div class="distance">' +
                                         '現在地からの距離： ' + display(distance) +
                                       '</div>' +
                                       '<div class="link">' +
                                         '<%= link_to karaoke_shop.name, karaoke_shop.homepage_link, :target=>["_blank"] %>' +
                                       '</div>'
                  var infoWindow = new google.maps.InfoWindow({ // 吹き出しの追加
                    content: window_content
                  });
                  marker.addListener('click', function() { // マーカーをクリックしたとき
                    infoWindow.open(map, marker); // 吹き出しの表示
                  });
                }
              }
            });
        <% end %>
      });
    }
    else{
  	  alert( "あなたの端末では、現在位置を取得できません。" ) ;
    }
  }
  function display(distance){
    if (distance >= 3000){
      return Math.round(distance/100)/10 + 'km'
    } else if (distance >= 1000){
      return Math.round(distance/10)/100 + 'km'
    } else{
      return Math.round(distance/10) * 10 + 'm'
    }
  }
</script>

app/views/fronts/new.html.erb
<h1>New Front</h1>

<%= render 'form', front: @front %>

<%= link_to 'Back', fronts_path %>

app/views/fronts/new_shop.html.erb
cccc

app/views/fronts/result.html.erb
<h2>検索結果</h2>

<div>
  <ul class="nav nav-tabs" role="tablist">
    <li class="active" role="presentation">
      <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab">料金順</a>
    </li>
    <li role="presentation">
      <a aria-controls="tab_b" data-toggle="tab" href="#tab_b" role="tab">店舗順</a>
    </li>
    <li role="presentation">
      <a aria-controls="tab_c" data-toggle="tab" href="#tab_c" role="tab">フリードリンクのみ表示</a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab_a" role="tabpanel">
      <p>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>店舗</th>
              <th>利用形態</th>
              <th>ドリンク形態</th>
              <th>開始時間</th>
              <th>終了時間</th>
              <th>料金</th>
            </tr>
          </thead>
          <tbody>
            <% @all_display_data.sort_by{|display_data| display_data.price}.each do |display_data| %>
              <tr>
                <td><%= link_to display_data.shop_name, display_data.homepage_link, :target=>["_blank"] %></td>
                <td><%= display_data.type %></td>
                <td><%= display_data.onedrink_price == 0 ? 'フリードリンク' : 'ワンドリンク制' %></td>
                <td><%= display_data.starttime.strftime("%H:%M") %></td>
                <td><%= display_data.endtime.strftime("%H:%M") %></td>
                <td><%= display_data.price %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </p>
    </div>
    <div class="tab-pane" id="tab_b" role="tabpanel">
      <p>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>店舗</th>
              <th>利用形態</th>
              <th>ドリンク形態</th>
              <th>開始時間</th>
              <th>終了時間</th>
              <th>料金</th>
            </tr>
          </thead>
          <tbody>
            <% @all_display_data.sort{|a,b| (a.karaoke_kind_id <=> b.karaoke_kind_id).notzero? || (a.price <=> b.price) }.each do |display_data| %>
              <tr>
                <td><%= display_data.shop_name %></td>
                <td><%= display_data.type %></td>
                <td><%= display_data.onedrink_price == 0 ? 'フリードリンク' : 'ワンドリンク制' %></td>
                <td><%= display_data.starttime.strftime("%H:%M") %></td>
                <td><%= display_data.endtime.strftime("%H:%M") %></td>
                <td><%= display_data.price %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </p>
    </div>
    <div class="tab-pane" id="tab_c" role="tabpanel">
      <p>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>店舗</th>
              <th>利用形態</th>
              <th>ドリンク形態</th>
              <th>開始時間</th>
              <th>終了時間</th>
              <th>料金</th>
            </tr>
          </thead>
          <tbody>
            <% @all_display_data.sort_by{|display_data| display_data.price}.each do |display_data| %>
              <% next if display_data.onedrink_price != 0 %>
              <tr>
                <td><%= display_data.shop_name %></td>
                <td><%= display_data.type %></td>
                <td>フリードリンク</td>
                <td><%= display_data.starttime.strftime("%H:%M") %></td>
                <td><%= display_data.endtime.strftime("%H:%M") %></td>
                <td><%= display_data.price %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </p>
    </div>
  </div>
</div>

app/views/fronts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_front_path(@front) %> |
<%= link_to 'Back', fronts_path %>

app/views/fronts/top.html.erb
<%= link_to '料金検索', calc_price_form_path, class:"btn btn-primary" %>

<%= link_to '店舗検索', karaoke_map_path, class:"btn btn-primary" %>