config/routes.rb
Rails.application.routes.draw do
  root "fronts#top"
  post "/result", to: "fronts#result"
  post "/map_search", to: "fronts#map_search"
  get "/calc_price_form", to: "fronts#calc_price_form"
  get "/karaoke_map", to: "fronts#karaoke_map"
  resources :karaoke_shops do
  end
end

app/models/karaoke_shop.rb
class KaraokeShop < ApplicationRecord
  attr_accessor :day_price, :night_price, :dayfree1_price, :nightfree1_price, :open_time, :close_time, :nightstart_time, :nightend_time,
                :dayfree1_starttime, :dayfree1_endtime, :nightfree1_starttime, :nightfree1_endtime, :day_onedrink, :night_onedrink, :dayfree1_onedrink, :dayfree2_onedrink, :nightfree1_onedrink, :nightfree2_onedrink, :starttime, :endtime, :date, :shop_data
  belongs_to :karaoke_kind
  belongs_to :area
  has_many :date_statuses, dependent: :delete_all
  has_many :shoptime_data, dependent: :delete_all
  has_one :member_price_datum, dependent: :delete
  has_one :freetime_datum, dependent: :delete
  has_one :onedrink_datum, dependent: :delete
  validates :name, presence: true

  def object(date,starttime,endtime)
    KaraokeKind.find(self.karaoke_kind_id).name_of_model.constantize.new(id: self.id, name: self.name, starttime: starttime, endtime: endtime, karaoke_kind_id: self.karaoke_kind_id, date: date, tax_include: self.tax_include, homepage_link: self.homepage_link, shop_data: register_param(date)).set_parameters
  end

  def set_parameters
    self.attributes = shop_data
    self
  end


  private

  def date_status(date)
    DateStatus.find_by(karaoke_shop_id: self.id, date: date).to_param
  end

  def register_param(date)
    shop_param(date).merge(price_param(date)).merge(freetime_param(date)).merge(onedrink_param(date))
  end

  def shop_param(date)
    ShoptimeDatum.find_by(karaoke_shop_id: self.id,date: date).to_param
  end

  def freetime_param(date)
    FreetimeDatum.find_by(karaoke_shop_id: self.id).to_param(date_status(date))
  end

  def price_param(date)
    MemberPriceDatum.find_by(karaoke_shop_id: self.id).to_param(date_status(date))
  end

  def onedrink_param(date)
    OnedrinkDatum.find_by(karaoke_shop_id: self.id).to_param(date_status(date))
  end

end

app/controllers/karaoke_shops_controller.rb
class KaraokeShopsController < ApplicationController
  before_action :set_karaoke_shop, only: [:show, :edit, :update, :destroy]

  # GET /karaoke_shops
  # GET /karaoke_shops.json
  def index
    @karaoke_shops = KaraokeShop.all
  end

  # GET /karaoke_shops/1
  # GET /karaoke_shops/1.json
  def show
  end

  # GET /karaoke_shops/new
  def new
    @karaoke_shop = KaraokeShop.new
  end

  # GET /karaoke_shops/1/edit
  def edit
  end

  # POST /karaoke_shops
  # POST /karaoke_shops.json
  def create
    @karaoke_shop = KaraokeShop.new(karaoke_shop_params)
      if @karaoke_shop.save
        @karaoke_shop.create_member_price_datum(member_price_data_params)
        @karaoke_shop.create_freetime_datum(freetime_data_params)
        @karaoke_shop.create_onedrink_datum(onedrink_data_params)
        @karaoke_shop.date_statuses.create(date_statuses_params)
        @karaoke_shop.shoptime_data.create(shoptime_data_params)
        redirect_to root_path, notice: 'Karaoke shop was successfully created.'
      else
        render :new
      end
  end

  # DELETE /karaoke_shops/1
  # DELETE /karaoke_shops/1.json
  def destroy
    @karaoke_shop.destroy
    respond_to do |format|
      format.html { redirect_to karaoke_shops_url, notice: 'Karaoke shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_karaoke_shop
      @karaoke_shop = KaraokeShop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def karaoke_shop_params
      params.require(:karaoke_shop).permit(:name, :karaoke_kind_id, :tax_include, :area_id)
    end

    def member_price_data_params
      params.require(:member_price_data).permit(:weekday_day_price, :holiday_day_price, :weekday_night_price, :holiday_night_price, :weekday_dayfree1_price, :holiday_dayfree1_price, :weekday_nightfree1_price, :holiday_nightfree1_price, :weekday_dayfree2_price, :holiday_dayfree2_price, :weekday_nightfree2_price, :holiday_nightfree2_price)
    end

    def freetime_data_params
      { weekday_dayfree1_starttime: OnlyTime.freetime(params[:freetime_data][:weekday_dayfree1_starttime],params[:freetime_data][:weekday_dayfree1_endtime])[:starttime], weekday_dayfree1_endtime: OnlyTime.freetime(params[:freetime_data][:weekday_dayfree1_starttime],params[:freetime_data][:weekday_dayfree1_endtime])[:endtime], weekday_dayfree1_limittime: params[:freetime_data][:weekday_dayfree1_limittime],
        weekday_nightfree1_starttime: OnlyTime.freetime(params[:freetime_data][:weekday_nightfree1_starttime],params[:freetime_data][:weekday_nightfree1_endtime])[:starttime], weekday_nightfree1_endtime: OnlyTime.freetime(params[:freetime_data][:weekday_nightfree1_starttime],params[:freetime_data][:weekday_nightfree1_endtime])[:endtime], weekday_nightfree1_limittime: params[:freetime_data][:weekday_nightfree1_limittime],
        holiday_dayfree1_starttime: OnlyTime.freetime(params[:freetime_data][:holiday_dayfree1_starttime],params[:freetime_data][:holiday_dayfree1_endtime])[:starttime], holiday_dayfree1_endtime: OnlyTime.freetime(params[:freetime_data][:holiday_dayfree1_starttime],params[:freetime_data][:holiday_dayfree1_endtime])[:endtime], holiday_dayfree1_limittime: params[:freetime_data][:holiday_dayfree1_limittime],
        holiday_nightfree1_starttime: OnlyTime.freetime(params[:freetime_data][:holiday_nightfree1_starttime],params[:freetime_data][:holiday_nightfree1_endtime])[:starttime], holiday_nightfree1_endtime: OnlyTime.freetime(params[:freetime_data][:holiday_nightfree1_starttime],params[:freetime_data][:holiday_nightfree1_endtime])[:endtime], holiday_nightfree1_limittime: params[:freetime_data][:holiday_nightfree1_limittime],
        weekday_dayfree2_starttime: OnlyTime.freetime(params[:freetime_data][:weekday_dayfree2_starttime],params[:freetime_data][:weekday_dayfree2_endtime])[:starttime], weekday_dayfree2_endtime: OnlyTime.freetime(params[:freetime_data][:weekday_dayfree2_starttime],params[:freetime_data][:weekday_dayfree2_endtime])[:endtime], weekday_dayfree2_limittime: params[:freetime_data][:weekday_dayfree2_limittime],
        weekday_nightfree2_starttime: OnlyTime.freetime(params[:freetime_data][:weekday_nightfree2_starttime],params[:freetime_data][:weekday_nightfree2_endtime])[:starttime], weekday_nightfree2_endtime: OnlyTime.freetime(params[:freetime_data][:weekday_nightfree2_starttime],params[:freetime_data][:weekday_nightfree2_endtime])[:endtime], weekday_nightfree2_limittime: params[:freetime_data][:weekday_nightfree2_limittime],
        holiday_dayfree2_starttime: OnlyTime.freetime(params[:freetime_data][:holiday_dayfree2_starttime],params[:freetime_data][:holiday_dayfree2_endtime])[:starttime], holiday_dayfree2_endtime: OnlyTime.freetime(params[:freetime_data][:holiday_dayfree2_starttime],params[:freetime_data][:holiday_dayfree2_endtime])[:endtime], holiday_dayfree2_limittime: params[:freetime_data][:holiday_dayfree2_limittime],
        holiday_nightfree2_starttime: OnlyTime.freetime(params[:freetime_data][:holiday_nightfree2_starttime],params[:freetime_data][:holiday_nightfree2_endtime])[:starttime], holiday_nightfree2_endtime: OnlyTime.freetime(params[:freetime_data][:holiday_nightfree2_starttime],params[:freetime_data][:holiday_nightfree2_endtime])[:endtime], holiday_nightfree2_limittime: params[:freetime_data][:holiday_nightfree2_limittime],
      }
    end

    def onedrink_data_params
      { weekday_day: params[:onedrink_data][:weekday][:day].to_bool, holiday_day: params[:onedrink_data][:holiday][:day].to_bool,
        weekday_night: params[:onedrink_data][:weekday][:night].to_bool, holiday_night: params[:onedrink_data][:holiday][:night].to_bool,
        weekday_dayfree1: params[:onedrink_data][:weekday][:dayfree1].to_bool, holiday_dayfree1: params[:onedrink_data][:holiday][:dayfree1].to_bool,
        weekday_dayfree2: params[:onedrink_data][:weekday][:dayfree2].to_bool, holiday_dayfree2: params[:onedrink_data][:holiday][:dayfree2].to_bool,
        weekday_nightfree1: params[:onedrink_data][:weekday][:nightfree1].to_bool, holiday_nightfree1: params[:onedrink_data][:holiday][:nightfree1].to_bool,
        weekday_nightfree2: params[:onedrink_data][:weekday][:nightfree2].to_bool, holiday_nightfree2: params[:onedrink_data][:holiday][:nightfree2].to_bool
      }
    end

    def date_statuses_params
      params[:date_statuses].values
    end

    def shoptime_data_params
      params[:shoptime_data].values.map{|data| {open_time: OnlyTime.shop_time(data[:open_time],data[:close_time])[:open_time], close_time: OnlyTime.shop_time(data[:open_time],data[:close_time])[:close_time], date: data[:date],
                                                nightstart_time: OnlyTime.set(data[:nightstart_time]), nightend_time: OnlyTime.set(data[:open_time]) == OnlyTime.set(data[:close_time]) ? OnlyTime.set(data[:nightend_time]) : nil
                                               }
                                       }
    end

end

app/helpers/karaoke_shops_helper.rb
module KaraokeShopsHelper
end

app/views/karaoke_shops/_form.html.erb
<%= form_with(model: karaoke_shop, local: true) do |form| %>
  <% if karaoke_shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(karaoke_shop.errors.count, "error") %> prohibited this karaoke_shop from being saved:</h2>

      <ul>
      <% karaoke_shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :karaoke_shop_name %>
  </div>

  <div class="field">
    <%= form.label :karaoke_kind_id %>
    <%= form.select :karaoke_kind_id, options_for_select(KaraokeKind.pluck(:name, :id))%>
  </div>

  <div class="field">
    <%= form.label :area_id %>
    <%= form.select :area_id, options_for_select(Area.pluck(:name, :id))%>
  </div>

  <div class="field">
    <%= form.label :tax_include %>
    <%= form.select :tax_include, options_for_select([["税込",true], ["税抜", false]])%>
  </div>

  <h2> プライスデータ　</h2>

  <div class="field">
    <%= form.label :weekday_day_price %>
    <%= number_field_tag "member_price_data[weekday_day_price]", :weekday_day_price %>
  </div>

  <div class="field">
    <%= form.label :holiday_day_price %>
    <%= number_field_tag "member_price_data[holiday_day_price]", :holiday_day_price %>
  </div>

  <div class="field">
    <%= form.label :weekday_night_price %>
    <%= number_field_tag "member_price_data[weekday_night_price]", :weekday_night_price %>
  </div>

  <div class="field">
    <%= form.label :holiday_night_price %>
    <%= number_field_tag "member_price_data[holiday_night_price]", :holiday_night_price %>
  </div>

  <div class="field">
    <%= form.label :weekday_dayfree1_price %>
    <%= number_field_tag "member_price_data[weekday_dayfree1_price]", :weekday_dayfree1_price %>
  </div>

  <div class="field">
    <%= form.label :holiday_dayfree1_price %>
    <%= number_field_tag "member_price_data[holiday_dayfree1_price]", :holiday_dayfree1_price %>
  </div>

  <div class="field">
    <%= form.label :weekday_nightfree1_price %>
    <%= number_field_tag "member_price_data[weekday_nightfree1_price]", :weekday_nightfree1_price %>
  </div>

  <div class="field">
    <%= form.label :holiday_nightfree1_price %>
    <%= number_field_tag "member_price_data[holiday_nightfree1_price]", :holiday_nightfree1_price %>
  </div>

  <div class="field">
    <%= form.label :weekday_dayfree2_price %>
    <%= number_field_tag "member_price_data[weekday_dayfree2_price]", :weekday_dayfree2_price %>
  </div>

  <div class="field">
    <%= form.label :holiday_dayfree2_price %>
    <%= number_field_tag "member_price_data[holiday_dayfree2_price]", :holiday_dayfree2_price %>
  </div>

  <div class="field">
    <%= form.label :weekday_nightfree2_price %>
    <%= number_field_tag "member_price_data[weekday_nightfree2_price]", :weekday_nightfree2_price %>
  </div>

  <div class="field">
    <%= form.label :holiday_nightfree2_price %>
    <%= number_field_tag "member_price_data[holiday_nightfree2_price]", :holiday_nightfree2_price %>
  </div>

  <h2> フリータイムデータ　</h2>

  <div class="field">
    <%= form.label :weekday_dayfree1_starttime %>
    <%= time_select "freetime_data[weekday_dayfree1_starttime]", :weekday_dayfree1_starttime, {minute_step: 10, prompt: {year: 2010}, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :weekday_dayfree1_endtime %>
    <%= time_select "freetime_data[weekday_dayfree1_endtime]", :weekday_dayfree1_endtime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :weekday_dayfree1_limittime %>
    <%= number_field_tag "freetime_data[weekday_dayfree1_limittime]", :weekday_dayfree1_limittime %>時間
  </div>

  <div class="field">
    <%= form.label :holiday_dayfree1_starttime %>
    <%= time_select "freetime_data[holiday_dayfree1_starttime]", :holiday_dayfree1_starttime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :holiday_dayfree1_endtime %>
    <%= time_select "freetime_data[holiday_dayfree1_endtime]", :holiday_dayfree1_endtime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :holiday_dayfree1_limittime %>
    <%= number_field_tag "freetime_data[holiday_dayfree1_limittime]", :holiday_dayfree1_limittime %>時間
  </div>

  <div class="field">
    <%= form.label :weekday_nightfree1_starttime %>
    <%= time_select "freetime_data[weekday_nightfree1_starttime]", :weekday_nightfree1_starttime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :weekday_nightfree1_endtime %>
    <%= time_select "freetime_data[weekday_nightfree1_endtime]", :weekday_nightfree1_endtime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :weekday_nightfree1_limittime %>
    <%= number_field_tag "freetime_data[weekday_nightfree1_limittime]", :weekday_nightfree1_limittime %>時間
  </div>

  <div class="field">
    <%= form.label :holiday_nightfree1_starttime %>
    <%= time_select "freetime_data[holiday_nightfree1_starttime]", :holiday_nightfree1_starttime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :holiday_nightfree1_endtime %>
    <%= time_select "freetime_data[holiday_nightfree1_endtime]", :holiday_nightfree1_endtime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :holiday_nightfree1_limittime %>
    <%= number_field_tag "freetime_data[holiday_nightfree1_limittime]", :holiday_nightfree1_limittime %>時間
  </div>

  <div class="field">
    <%= form.label :weekday_dayfree2_starttime %>
    <%= time_select "freetime_data[weekday_dayfree2_starttime]", :weekday_dayfree2_starttime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :weekday_dayfree2_endtime %>
    <%= time_select "freetime_data[weekday_dayfree2_endtime]", :weekday_dayfree2_endtime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :weekday_dayfree2_limittime %>
    <%= number_field_tag "freetime_data[weekday_dayfree2_limittime]", :weekday_dayfree2_limittime %>時間
  </div>

  <div class="field">
    <%= form.label :holiday_dayfree2_starttime %>
    <%= time_select "freetime_data[holiday_dayfree2_starttime]", :holiday_dayfree2_starttime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :holiday_dayfree2_endtime %>
    <%= time_select "freetime_data[holiday_dayfree2_endtime]", :holiday_dayfree2_endtime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :holiday_dayfree2_limittime %>
    <%= number_field_tag "freetime_data[holiday_dayfree2_limittime]", :holiday_dayfree2_limittime %>時間
  </div>

  <div class="field">
    <%= form.label :weekday_nightfree2_starttime %>
    <%= time_select "freetime_data[weekday_nightfree2_starttime]", :weekday_nightfree2_starttime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :weekday_nightfree2_endtime %>
    <%= time_select "freetime_data[weekday_nightfree2_endtime]", :weekday_nightfree2_endtime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :weekday_nightfree2_limittime %>
    <%= number_field_tag "freetime_data[weekday_nightfree2_limittime]", :weekday_nightfree2_limittime %>時間
  </div>

  <div class="field">
    <%= form.label :holiday_nightfree2_starttime %>
    <%= time_select "freetime_data[holiday_nightfree2_starttime]", :holiday_nightfree2_starttime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :holiday_nightfree2_endtime %>
    <%= time_select "freetime_data[holiday_nightfree2_endtime]", :holiday_nightfree2_endtime, {minute_step: 10, include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :holiday_nightfree2_limittime %>
    <%= number_field_tag "freetime_data[holiday_nightfree2_limittime]", :holiday_nightfree2_limittime %>時間
  </div>

  <h2> 曜日データ　</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>曜日</th>
        <th>day</th>
        <th>night</th>
        <th>day_freetime1</th>
        <th>day_freetime2</th>
        <th>night_freetime1</th>
        <th>night_freetime2</th>
      </tr>
    </thead>
    <tbody>
      <% EasySettings.date.each_with_index do |date,i| %>
        <tr>
          <td><%= date %></td>
          <td><%= select_tag "date_statuses[date#{i}][day]", options_for_select(EasySettings.date_statuses) %></td>
          <td><%= select_tag "date_statuses[date#{i}][night]", options_for_select(EasySettings.date_statuses) %></td>
          <td><%= select_tag "date_statuses[date#{i}][day_freetime1]", options_for_select(EasySettings.date_statuses) %></td>
          <td><%= select_tag "date_statuses[date#{i}][day_freetime2]", options_for_select(EasySettings.date_statuses) %></td>
          <td><%= select_tag "date_statuses[date#{i}][night_freetime1]", options_for_select(EasySettings.date_statuses) %></td>
          <td><%= select_tag "date_statuses[date#{i}][night_freetime2]", options_for_select(EasySettings.date_statuses) %></td>
          <%= hidden_field_tag "date_statuses[date#{i}][date]", date %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2> ショップ情報 </h2>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>曜日</th>
        <th>open_time</th>
        <th>close_time</th>
        <th>nightstart_time</th>
        <th>nightend_time</th>
      </tr>
    </thead>
    <tbody>
      <% EasySettings.date.each_with_index do |date,i| %>
        <tr>
          <td><%= date %></td>
          <td><%= time_select "shoptime_data[date#{i}][open_time]", :open_time, {minute_step: 10, include_blank: true} %></td>
          <td><%= time_select "shoptime_data[date#{i}][close_time]", :close_time, {minute_step: 10, include_blank: true} %></td>
          <td><%= time_select "shoptime_data[date#{i}][nightstart_time]", :nightstart_time, {minute_step: 10, include_blank: true} %></td>
          <td><%= time_select "shoptime_data[date#{i}][nightend_time]", :nightend_time, {minute_step: 10, include_blank: true} %></td>
          <%= hidden_field_tag "shoptime_data[date#{i}][date]", date %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2> ワンドリンク情報 </h2>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>type</th>
        <th>WEEKDAY</th>
        <th>HOLIDAY</th>
      </tr>
    </thead>
    <tbody>
      <% EasySettings.time_types.each do |type| %>
        <tr>
          <td><%= type %></td>
          <td><%= select_tag "onedrink_data[weekday][#{type}]", options_for_select([["有",true], ["無", false]]), include_blank: true %></td>
          <td><%= select_tag "onedrink_data[holiday][#{type}]", options_for_select([["有",true], ["無", false]]), include_blank: true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/karaoke_shops/edit.html.erb
<h1>Editing Karaoke Shop</h1>

<%= render 'form', karaoke_shop: @karaoke_shop %>

<%= link_to 'Show', @karaoke_shop %> |
<%= link_to 'Back', karaoke_shops_path %>

app/views/karaoke_shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Karaoke Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Day price</th>
      <th>Night price</th>
      <th>Dayfree1 price</th>
      <th>Nightfree1 price</th>
      <th>Open time</th>
      <th>Close time</th>
      <th>Nightstart time</th>
      <th>Dayfree1 start time</th>
      <th>Dayfree1 endtime</th>
      <th>Nightfree1 start time</th>
      <th>Nightfree1 endtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @karaoke_shops.each do |karaoke_shop| %>
      <tr>
        <td><%= karaoke_shop.name %></td>
        <td><%= karaoke_shop.day_price %></td>
        <td><%= karaoke_shop.night_price %></td>
        <td><%= karaoke_shop.dayfree1_price %></td>
        <td><%= karaoke_shop.nightfree1_price %></td>
        <td><%= karaoke_shop.open_time %></td>
        <td><%= karaoke_shop.close_time %></td>
        <td><%= karaoke_shop.nightstart_time %></td>
        <td><%= karaoke_shop.dayfree1_start_time %></td>
        <td><%= karaoke_shop.dayfree1_endtime %></td>
        <td><%= karaoke_shop.nightfree1_start_time %></td>
        <td><%= karaoke_shop.nightfree1_endtime %></td>
        <td><%= link_to 'Show', karaoke_shop %></td>
        <td><%= link_to 'Edit', edit_karaoke_shop_path(karaoke_shop) %></td>
        <td><%= link_to 'Destroy', karaoke_shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Karaoke Shop', new_karaoke_shop_path %>

app/views/karaoke_shops/new.html.erb
<h1>New Karaoke Shop</h1>

<%= render 'form', karaoke_shop: @karaoke_shop %>

<%= link_to 'トップへ戻る', root_path %>

app/views/karaoke_shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @karaoke_shop.name %>
</p>

<p>
  <strong>Day price:</strong>
  <%= @karaoke_shop.day_price %>
</p>

<p>
  <strong>Night price:</strong>
  <%= @karaoke_shop.night_price %>
</p>

<p>
  <strong>Dayfree1 price:</strong>
  <%= @karaoke_shop.dayfree1_price %>
</p>

<p>
  <strong>Nightfree1 price:</strong>
  <%= @karaoke_shop.nightfree1_price %>
</p>

<p>
  <strong>Open time:</strong>
  <%= @karaoke_shop.open_time %>
</p>

<p>
  <strong>Close time:</strong>
  <%= @karaoke_shop.close_time %>
</p>

<p>
  <strong>Nightstart time:</strong>
  <%= @karaoke_shop.nightstart_time %>
</p>

<p>
  <strong>Dayfree1 start time:</strong>
  <%= @karaoke_shop.dayfree1_start_time %>
</p>

<p>
  <strong>Dayfree1 endtime:</strong>
  <%= @karaoke_shop.dayfree1_endtime %>
</p>

<p>
  <strong>Nightfree1 start time:</strong>
  <%= @karaoke_shop.nightfree1_start_time %>
</p>

<p>
  <strong>Nightfree1 endtime:</strong>
  <%= @karaoke_shop.nightfree1_endtime %>
</p>

<%= link_to 'Edit', edit_karaoke_shop_path(@karaoke_shop) %> |
<%= link_to 'Back', karaoke_shops_path %>